language: go
go_import_path: github.com/gajananan/integrity-enforcer/enforcer
go:
  - 1.14.x

env:
- GO111MODULE=on

script:
- go test -v github.com/gajananan/integrity-enforcer/enforcer/pkg/util/sign/x509
