language: go

service:
  - docker

go:
  - 1.x

#before_install:
#  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
  
script:
  - export TRAVIS_BUILD_DIR=/home/travis/gopath/src/github.com/gajananan/integrity-enforcer/travis_build
  - echo $GOPATH
  - ${TRAVIS_BUILD_DIR}/install-dependencies.sh
  - pwd
  - pwd
  - ls
  - export IE_REPO_ROOT=/home/travis/gopath/src/github.com/gajananan/integrity-enforcer
  - export IE_ENV=remote
  #- ./develop/scripts/build_images.sh
  - ./scripts/make_bundle.sh
