language: go
go_import_path: github.com/gajananan/integrity-enforcer/enforcer
go:
  - 1.14.x

env:
- "PATH=/home/travis/gopath/bin:$PATH"

script:
- go test -v github.com/gajananan/integrity-enforcer/enforcer/pkg/util/sign/x509
