language: go

go:
   - 1.15.x

env:
 global:
  - GO111MODULE=auto
  - GOFLAGS="-mod=readonly"

cache:
 directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod
  
git:
 depth: 1
 autocrlf: input  
 
 before_install:
 - ${TRAVIS_BUILD_DIR}/.travis/run-parts ${TRAVIS_BUILD_DIR}/.travis/deps.d/${TRAVIS_OS_NAME}
 
 go_import_path: github.com/gajananan/integrity-enforcer/enforcer
 
 script:
 - go test -v github.com/gajananan/integrity-enforcer/enforcer/pkg/util/sign/x509
